### ISSUE TITLE
Why redefine drop command

### ISSUE THREAD

**Issue by hjpotter92** [HiT-Hi-FiT-Hai/hhfh-issues#12]
Is there a necessity for creating a new drop command? PtokaX already provides it.

Code where `drop` command is defined: https://github.com/HiT-Hi-FiT-Hai/ptokax-scripts/blob/master/files/custcom.lua#L75

```
!drop <nick> <reason> - disconnect with tempban.
```

**Comment by siddhu323** [comment]
The default drop command of PtokaX disconnects with a tempban of 20 mins.
Most of the commands in this script were written to emulate the commands of
YnHub , in which drop meant disconnection only.
There is no such command provided by PtokaX. Its drop command resembles the
kick command of YnHub, which has been defined in this script with a tempban
of 10 mins.
