### ISSUE TITLE
subroom.lua logs an error every so often

### ISSUE THREAD

**Issue by hjpotter92** [HiT-Hi-FiT-Hai/hhfh-issues#13]
```
scripts/subroom.lua:59: attempt to index local 'sCmd' (a nil value)
```

The above is logged in the PtokaX `script.log` file every once in a while.

**Comment by siddhu323** [comment]
This happens because of the underlying assumption in line 59 that all messages sent to the chatroom are from subscribed users OR begin with a [-+*/!#?]. Every once in a while someone who is not subscribed sends a message which doesnt begin with [-+*/!#?].
