### ISSUE TITLE
Got permanently banned error

### ISSUE THREAD

**Issue by Hema-Velappan** [HiT-Hi-FiT-Hai/hhfh-issues#16]
Hi,
My IP has been permanently banned for no reason. pls chk the same, and lift the ban. Thanks..

**Comment by Hema-Velappan** [comment]
Nick name : Megatron
File size shared : 90GB
connected via lan only; i had a pbm with dc ever since i gave a system restore, it used to search but i couldnt download anything, so i gave the passive mode option (cuz it dint work  even wen the firewall settings to allow dc ++ was changed)  and it workd fine for one day.. Then yesterday night i was asked for password for connecting to 10.105.65.1, and unfortunately i gave some random stuff and i got permanently banned :( pls help me with this issue and also suggest wat cud be done for the download issue apart from giving passive mode option. 
Error :  <PtokaX> Sorry you are permanently banned.
IP: 10.102.19.12
Reason: 3x bad password for nick Megatron

**Comment by hjpotter92** [comment]
> My IP has been permanently banned for no reason.

The hub software **always mentions** the reason behind a ban.

> i gave the passive mode option (cuz it dint work even wen the firewall settings to allow dc ++ was changed)

Please don't use connect to the hub in Passive mode. It unnecessarily burdens the machine for each action you perform (search, download, connect etc.)

> yesterday night i was asked for password for connecting to 10.105.65.1, and unfortunately i gave some random stuff and i got permanently banned

Someone (maybe you?) has registered the nickname you are currently using. This is done so as to keep a unique identity on the hub. If you have forgotten the password (or you never registered) then change you nick to something else and retry.

> i got permanently banned :( pls help me with this issue

I've unbanned the IP you mentioned in the issue.

> also suggest wat cud be done for the download issue apart from giving passive mode option. 

You'd have to provide details such as which anti-virus application do you use; which firewall you have installed; what DC++ settings you have in place etc.

**Comment by Hema-Velappan** [comment]
Thank u, its working now :)
