### ISSUE TITLE
Error with eat.lua

### ISSUE THREAD

**Issue by chandraananya** [HiT-Hi-FiT-Hai/hhfh-issues#17]
Hi,
This post is related to the error that I had emailed to hjpotter92.
I use PtokaX 0.5.0.2 on Windows 7 x64 for running the 24 x 7 LNMIIT Server. I decided to load the scripts that were offered by you in the hhfh package.
All scripts run successfully except for the eat.lua
I get this error in the syntax checker of PtokaX.
../ptokax_dc_hub/0.5.0.2-Lua5.2.3-x64/scripts/files/mcunsubs.txt: No such file or directory

The previous errors related to the backslash '\' in expel.lua were resolved by removing it and then compiling. 
What is wrong ?

**Comment by chandraananya** [comment]
Hi,
I would also like to add that the script expel.lua in ptokax/scripts/files of  the hhfh package is now giving me a new error.
Syntax [string"..."]:5 attempt to concatenate a global 'path' (a nil value)
I am sorry i forgot to mention this in my email to you too.

**Comment by siddhu323** [comment]
Hi,

For your first problem I would suggest you to create an empty text file of that name in the that directory.
As to your second problem - are you trying to run expel.lua as an independent script ? If so , don't do that - just run eat.lua . Only run scripts in the main directory - all other files are dependent on them.

**Comment by chandraananya** [comment]
Thank you. The script now works fine.
:)
(Y) hhfh.
