### ISSUE TITLE
No downloading despite sharing the required data.

### ISSUE THREAD

**Issue by sudeepdino008** [HiT-Hi-FiT-Hai/hhfh-issues#24]
I have shared 113 GB of data on linuxdc++. I am able to search for stuff but can't download it. Heading to the Hit Hai Fit Hai tab gives me the message: "minimum sharesize required to search and download is 64 GiB."

Please help resolve this issue

**Comment by hjpotter92** [comment]
1. Please provide your nickname and IP.
2. Would you be able to provide a screenshot to support your argument?

**Comment by sudeepdino008** [comment]
nickname: bazinga
IP: 10.102.67.94

![screenshot from 2015-01-14 13 44 29](https://cloud.githubusercontent.com/assets/1736155/5735888/1eeff9a4-9bf4-11e4-970e-69b6e5211c94.png)
![screenshot from 2015-01-14 13 44 57](https://cloud.githubusercontent.com/assets/1736155/5735889/1ef6f72c-9bf4-11e4-9ba9-df9d6d07c36f.png)

**Comment by hjpotter92** [comment]
Can you confirm whether bidirectional UDP connections are allowed or not? Please remain connected to the hub for the duration of resolving this issue.

Also check directory permissions of `~/.config/dc++/`. I don't think it is a permissions issue, but it wouldn't hurt.

**Comment by sudeepdino008** [comment]
How do we check for the allowance of bidirectional UDP connections? I am sending a screenshot, maybe this is what you mean...
![screenshot from 2015-01-14 20 33 25](https://cloud.githubusercontent.com/assets/1736155/5740782/c5226202-9c2c-11e4-80a6-fe4f27e03e5e.png)

There is a .dc++/ folder to which I did: chmod 755 /folder -R

**Comment by Amarnathpg123** [comment]
Here are some solutions I observed connecting through linuxdc++:
i) In connections choose  Active mode and add port 8080 to all connections.
ii) Use Direct connection for Outgoing.
iii) Disable firewall in the linux distribution or allow the dc++ through firewall/antivirus.
iv) Check the upload slots, make it available.
iv) Overall upload some decent 100GiB data in sharing.
