### ISSUE TITLE
Add hub details to hhfh-docs

### ISSUE THREAD

**Issue by nishithshah2211** [HiT-Hi-FiT-Hai/hhfh-issues#26]
@hjpotter92 Should we add details about how the hub is running? By details I mean things like hub machine specs, VM specs, architecture etc. This will help any new contributors.

**Comment by hjpotter92** [comment]
Yeah. I might do so over this weekend!

**Comment by hjpotter92** [comment]
I've added the basic information for now to [`sysinfo.md`](https://github.com/HiT-Hi-FiT-Hai/hhfh-docs/blob/master/sysinfo.md) file.
