### ISSUE TITLE
ncdc gets banned for connecting in passive mode

### ISSUE THREAD

**Issue by amrav** [HiT-Hi-FiT-Hai/hhfh-issues#32]
[ncdc](http://dev.yorhel.nl/ncdc) connects in active mode, and uses the machine IP. It's still getting banned for connecting in passive mode. I've opened an [issue](http://dev.yorhel.nl/ncdc/bug/76) for ncdc which has some more information about what I've tried. It would be really helpful if I could know exactly why ncdc gets banned on HHFH.

![screen shot 2015-04-13 at 17 52 57](https://cloud.githubusercontent.com/assets/1186303/7116063/fa6eb3c8-e20b-11e4-822b-984898a7dd36.png)

**Comment by hjpotter92** [comment]
Yorhel, ncdc's author, has fixed this [behaviour](http://dev.yorhel.nl/ncdc/bug/76):

> Implemented your suggestion: http://g.blicky.net/ncdc.git/commit?id=e7bfec9
> 
> Haven't extensively tested this yet, but it's looking good so far.
