### ISSUE TITLE
No Downloading and Passive Mode Problem

### ISSUE THREAD

**Issue by DjSnipe** [HiT-Hi-FiT-Hai/hhfh-issues#35]
When I try to download in active mode connection timeout is shown and when I switch to Auto Detect setting I'm being banned. Earlier this setting worked but not now. I am not being able to download anything from the hub. I have tried all the setting but nothing worked out. I've also tried by turning off the network firewall but it was of no use.

**Comment by hjpotter92** [comment]
Please go through #36.
