### ISSUE TITLE
 The country-level IPv6 GeoIP database could not be updated

### ISSUE THREAD

**Issue by Aviarya9** [HiT-Hi-FiT-Hai/hhfh-issues#36]
I am not able to search and download anything and the above message ( The country-level IPv6 GeoIP database could not be updated) shows in the system log. Please help.

**Comment by hjpotter92** [comment]
The GeoIP database updation is irrelevant to the actual issue. Please go through #33 and #15.

**Comment by Aviarya9** [comment]
Nick : Mickeyadds
IP : 10.117.82.145
share size : 118 Gb
Please help me. I am not able to download anything.

**Comment by hjpotter92** [comment]
@Aviarya9 As commented on the linked issues, check your firewall settings.

**Comment by Aviarya9** [comment]
Well I could not find firewall settings. Is it related to my DC or my computer?

**Comment by hjpotter92** [comment]
@Aviarya9 If you're using an antivirus application, check their support sites to see if they bundle a firewall with them. Most of AV suites provide an internet firewall (like AVG, ESET, Norton etc.). If the former is not applicable, and you're on a Windows system; go to _Control Panel_ and check the firewall settings there. Allow DC++ full access for incoming and outgoing connections.

**Comment by Aviarya9** [comment]
Thank you so much sir. The problem was with firewall settings only and its working now.
