### ISSUE TITLE
Changes in right click menu

### ISSUE THREAD

**Issue by AjayRamanathan** [HiT-Hi-FiT-Hai/hhfh-issues#6]
Order needs rearranging so that Latest and Info-bot are first after send Offliner to the user, while Rules and File Report are pushed down.

**Comment by hjpotter92** [comment]
If you remember the old order of list (the one where you had to explicitly ask for Offliner and Info commands); you'll notice that they are graded in descending order of usage and/or requirement.

_Help_ in each section has been put at the very bottom though! As for the new list order, it'll be made random with next commit or so.

![capture_2013-05-16_191718_703_001](https://f.cloud.github.com/assets/3393533/541241/6880cfac-c203-11e2-8c87-31e358409861.png)

**Comment by hjpotter92** [comment]
@AjayRamanathan I guess the menu indeed needs a redesign now. Also, we'd need to include some more user commands in there. ;)

Reopened the issue...

**Comment by hjpotter92** [comment]
A rough sketch of commands is publicly available on gist (https://gist.github.com/hjpotter92/5788888). I'll be updating it soon tonight. Comments and suggestions are welcome.

**Comment by hjpotter92** [comment]
Fixed via HiT-Hi-FiT-Hai/ptokax-scripts@ff97bb0880926b29b3c8e31672fa50ef401557c1
